# 配置中心环境定义

# 基本配置
[base]
    # 数据文件存储路径
    data_dir="/mnt/share/src/conf/_examples/"
    #环境
    env="dev"
    # 优先取用何种配置,当配置中心项目名称和配置文件名称冲突时以优先加载的为准  1 文件配置 2 配置中心
    # 当本地目录有和线上配置中心项目名称(object)相同时配置中心的同步将失效
    # 建议的配置是 2
    first=1
# 以下是非必须的选项
[base.options]
    # 配置缓存路径,默认 $data_dir/cache
    cache_path="/mnt/share/src/conf/_examples/cache"
    # 日志路径 默认 $data_dir/log
    log_tath="/mnt/share/src/conf/_examples/log"
    # 配置文件存放目录，将会解析并加载该目录下的所有配置文件 默认$data_dir/conf
    config_path="/mnt/share/src/conf/_examples/conf"

# 配置中心配置
[xdiamond]
	#groupId 对应groupId
	group_id = "web"
	#artifactId 对应project 默认test
	artifact_id = "golang-test"
	#string 对应环境 这里没有配置的话会取 base.env
	profile = "dev"
	#version 配置版本,指project的版本 默认 1.0
	version ="1.0"
	#secretKey auth认证key 默认 ""
	secret_key ="68bq57jhxmi"
	#address 配置中心服务器地址 不允许添加http等前缀，ip+port  或 域名+port
	address ="10.0.200.53:8089"
    #配置中心数据同步方式,可选数值 http,tcp 。http拉取数据方式在程序启动时同步一次,默认tcp
    conn_mode="http"